#!/usr/bin/env python3
"""Atomic route/certificate reload and conservative planned-change system checks.

Run against the config generated by ../reload_fixtures.py, mounted writable for
this driver. Uses only disposable fixture configuration and isolated database.
Existing clients keep original service generations. This checks no forced drops
of existing work; it does not claim automatic promotion or seamless new logins.
"""
import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
import http.client
import json
from pathlib import Path
import socket
import ssl
import struct
import threading
import time

import psycopg


def request(args, path, method='POST', token=True):
    connection = http.client.HTTPConnection(args.host, args.operations_port, timeout=5)
    headers = {'Authorization': 'Bearer ' + args.token} if token else {}
    connection.request(method, path, body=None, headers=headers)
    response = connection.getresponse()
    body = response.read()
    connection.close()
    return response.status, json.loads(body)


def connect(args):
    return psycopg.connect(host=args.host, port=args.port, dbname='reload_transaction',
              user='postgres', autocommit=True, sslmode='verify-full',
              sslrootcert=str(args.fixtures / 'ca.pem'), connect_timeout=5)


def fingerprint(args):
    context = ssl.create_default_context(cafile=str(args.fixtures / 'ca.pem'))
    with socket.create_connection((args.host, args.port), timeout=5) as stream:
        stream.sendall(struct.pack('!II', 8, 80877103))
        assert stream.recv(1) == b'S'
        with context.wrap_socket(stream, server_hostname=args.host) as encrypted:
            return hashlib.sha256(encrypted.getpeercert(binary_form=True)).hexdigest()


def cancel_query(connection):
    started = threading.Event()
    def sleeping():
        started.set()
        try:
            connection.execute('SELECT pg_catalog.pg_sleep(8)')
        except psycopg.errors.QueryCanceled:
            return
        raise AssertionError('query did not cancel')
    with ThreadPoolExecutor(max_workers=1) as executor:
        task = executor.submit(sleeping)
        assert started.wait(2)
        time.sleep(.25)
        connection.cancel()
        task.result(timeout=4)
    assert connection.execute('SELECT 42').fetchone()[0] == 42


def run(args):
    config = args.fixtures / 'proxy.toml'
    original = config.read_text()
    old = None
    try:
        old = connect(args)
        old.execute("SET application_name='old-generation'")
        before = fingerprint(args)
        # Different signed certificate/key is actually loaded for future TLS handshakes.
        rotated = original.replace('server-1.pem', 'server-2.pem').replace('server-1-key.pem', 'server-2-key.pem')
        config.write_text(rotated)
        status, state = request(args, '/reload')
        assert status == 200, (status, state)
        generation = state['generation']
        assert generation >= 2
        assert fingerprint(args) != before
        with connect(args) as fresh:
            assert fresh.execute('SELECT 42').fetchone()[0] == 42
        assert old.execute('SHOW application_name').fetchone()[0] == 'old-generation'
        cancel_query(old)
        print('PASS certificate rotation, retained client state and old-generation cancellation', flush=True)

        # Staging failures cannot mutate the live generation or frontend certificate.
        current = fingerprint(args)
        for invalid in [rotated.replace('pool_size = 2', 'pool_size = 0'),
                        rotated.replace('server-2.pem', 'missing-server.pem'),
                        rotated.replace('workers = 2', 'workers = 3')]:
            config.write_text(invalid)
            status, error = request(args, '/reload')
            assert status == 409 and 'error' in error, (status, error)
            assert fingerprint(args) == current
            assert old.execute('SELECT 42').fetchone()[0] == 42
        config.write_text(rotated)
        print('PASS invalid configuration/certificate/static runtime changes preserve live service', flush=True)

        status, state = request(args, '/switchover/prepare')
        assert status == 200 and state['phase'] == 'draining'
        assert state['generation'] == generation
        assert request(args, '/ready', method='GET', token=False)[0] == 503
        try:
            connect(args)
        except psycopg.OperationalError:
            pass
        else:
            raise AssertionError('new login was admitted during drain')
        # Cancellation control connections still decode during login quiescence.
        cancel_query(old)
        status, error = request(args, '/switchover/commit')
        assert status == 409 and 'error' in error
        old.close()
        old = None
        deadline = time.monotonic() + 5
        while True:
            status, state = request(args, '/switchover/commit')
            if status == 200:
                break
            assert time.monotonic() < deadline, (status, state)
            time.sleep(.05)
        assert state['generation'] == generation + 1
        assert state['phase'] == 'running'
        assert request(args, '/ready', method='GET', token=False)[0] == 200
        with connect(args) as fresh:
            assert fresh.execute('SELECT 42').fetchone()[0] == 42
        print('PASS quiesce, cancel existing query, deny early commit, drain and resume', flush=True)

        status, state = request(args, '/switchover/prepare')
        assert status == 200
        status, state = request(args, '/switchover/abort')
        assert status == 200 and state['generation'] == generation + 1
        assert state['phase'] == 'running'
        with connect(args) as fresh:
            assert fresh.execute('SELECT 42').fetchone()[0] == 42
        print('PASS abort resumes original generation', flush=True)
        print('4/4 reload and planned-change checks passed', flush=True)
    finally:
        config.write_text(original)
        if old is not None:
            old.close()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--host', default='host.docker.internal')
    parser.add_argument('--port', type=int, default=6444)
    parser.add_argument('--operations-port', type=int, default=6452)
    parser.add_argument('--fixtures', type=Path, required=True)
    parser.add_argument('--token', default='pgproxy-reload-test-token-0000000000')
    run(parser.parse_args())


if __name__ == '__main__':
    main()
