FROM debian:bookworm-slim
RUN apt-get update -qq \
 && apt-get install -y -qq --no-install-recommends pgbouncer ca-certificates >/dev/null \
 && rm -rf /var/lib/apt/lists/*
RUN pgbouncer --version
ENTRYPOINT ["pgbouncer", "/etc/pgbouncer/pgbouncer.ini"]
