[package]
name = "pgproxy-cli"
description = "The pgproxy binary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "pgproxy"
path = "src/main.rs"

[dependencies]
pgproxy-core = { path = "../pgproxy-core" }
pgproxy-wire = { path = "../pgproxy-wire" }
clap.workspace = true
tracing.workspace = true
